### ISSUE TITLE
Mapping values are not allowed in this context.

### ISSUE THREAD

**Issue by damondouglas** [seaneagan/den#16]
```
$ den install git://github.com/seaneagan/prompt.git -sgit
```

results in

```
Unhandled exception:
Uncaught Error: Error on line 5, column 14 of pubspec.yaml: Mapping values are not allowed in this context.
  prompt: git: git://github.com/seaneagan/prompt.git
             ^
Stack Trace:
#0      Scanner._fetchValue (package:yaml/src/scanner.dart:720)
#1      Scanner._fetchNextToken (package:yaml/src/scanner.dart:455)
#2      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:338)
#3      Scanner.peek (package:yaml/src/scanner.dart:319)
#4      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:423)
#5      Parser._stateMachine (package:yaml/src/parser.dart:88)
#6      Parser.parse (package:yaml/src/parser.dart:49)
#7      Loader._loadMapping (package:yaml/src/loader.dart:165)
#8      Loader._loadNode (package:yaml/src/loader.dart:83)
#9      Loader._loadMapping (package:yaml/src/loader.dart:163)
#10     Loader._loadNode (package:yaml/src/loader.dart:83)
#11     Loader._loadDocument (package:yaml/src/loader.dart:63)
#12     Loader.load (package:yaml/src/loader.dart:55)
#13     loadYamlDocument (package:yaml/yaml.dart:53)
#14     loadYamlNode (package:yaml/yaml.dart:44)
#15     Pubspec.contents= (package:den/src/pub.dart:20)
#16     Pubspec.addDependency (package:den/src/pub.dart:163)
#17     Object&BumpCommand&FetchCommand&InstallCommand.install.<anonymous closure>.<anonymous closure> (package:den/src/commands/install.dart:64)
#18     List.forEach (dart:core-patch/array.dart:129)
#19     Object&BumpCommand&FetchCommand&InstallCommand.install.<anonymous closure> (package:den/src/commands/install.dart:63)
#20     _RootZone.runUnary (dart:async/zone.dart:1155)
#21     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#22     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#23     _Future._completeWithValue (dart:async/future_impl.dart:358)
#24     Future.wait.<anonymous closure> (dart:async/future.dart:282)
#25     _RootZone.runUnary (dart:async/zone.dart:1155)
#26     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#27     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#28     _Future._complete (dart:async/future_impl.dart:348)
#29     Future.Future.<anonymous closure> (dart:async/future.dart:118)
#30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:12)
#31     _handleTimeout (dart:io/timer_impl.dart:292)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:130)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
```

Is this related to http://dartbug.com/21841?

**Comment by seaneagan** [comment]
@damondouglas thanks for the report!  fixed in v0.1.5.
