### ISSUE TITLE
den uninstall polymer

### ISSUE THREAD

**Issue by zoechi** [seaneagan/den#8]
```
 (master) $ den uninstall polymer
orderedKeys: [browser, polymer, paper_elements]
Unhandled exception:
Error on line 11, column 19 of pubspec.yaml: Mapping values are not allowed in this context.
    paper_elements: '>=0.6.0 <0.7.0'
                  ^
#0      Scanner._fetchValue (package:yaml/src/scanner.dart:720)
#1      Scanner._fetchNextToken (package:yaml/src/scanner.dart:455)
#2      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:338)
#3      Scanner.peek (package:yaml/src/scanner.dart:319)
#4      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:423)
#5      Parser._stateMachine (package:yaml/src/parser.dart:88)
#6      Parser.parse (package:yaml/src/parser.dart:49)
#7      Loader._loadMapping (package:yaml/src/loader.dart:165)
#8      Loader._loadNode (package:yaml/src/loader.dart:83)
#9      Loader._loadMapping (package:yaml/src/loader.dart:163)
#10     Loader._loadNode (package:yaml/src/loader.dart:83)
#11     Loader._loadDocument (package:yaml/src/loader.dart:63)
#12     Loader.load (package:yaml/src/loader.dart:55)
#13     loadYamlDocument (package:yaml/yaml.dart:53)
#14     loadYamlNode (package:yaml/yaml.dart:44)
#15     Pubspec.contents= (package:den/src/pub.dart:20)
#16     Pubspec.undepend.removeFromGroup (package:den/src/pub.dart:109)
#17     Pubspec.undepend (package:den/src/pub.dart:114)
#18     Den.uninstall.<anonymous closure> (package:den/src/den.dart:106)
#19     Object&ListMixin.fold (dart:collection/list.dart:200)
#20     Den.uninstall (package:den/src/den.dart:105)
#21     _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:539)
#22     _LocalInstanceMirror.delegate (dart:mirrors-patch/mirrors_impl.dart:414)
#23     DeclarationScript._handleSubCommands (package:unscripted/src/script_impl.dart:129)
#24     DeclarationScript._handleResults (package:unscripted/src/script_impl.dart:103)
#25     ScriptImpl.execute (package:unscripted/src/script_impl.dart:45)
#26     main (http://localhost:52691/den.dart:6)
#27     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:203)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:141)
/home/myuser/.pub-cache/bin/den: 12: /home/myuser/.pub-cache/bin/den: [[: not found
orderedKeys: [browser, polymer, paper_elements]
Unhandled exception:
Error on line 11, column 19 of pubspec.yaml: Mapping values are not allowed in this context.
    paper_elements: '>=0.6.0 <0.7.0'
                  ^
#0      Scanner._fetchValue (package:yaml/src/scanner.dart:720)
#1      Scanner._fetchNextToken (package:yaml/src/scanner.dart:455)
#2      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:338)
#3      Scanner.peek (package:yaml/src/scanner.dart:319)
#4      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:423)
#5      Parser._stateMachine (package:yaml/src/parser.dart:88)
#6      Parser.parse (package:yaml/src/parser.dart:49)
#7      Loader._loadMapping (package:yaml/src/loader.dart:165)
#8      Loader._loadNode (package:yaml/src/loader.dart:83)
#9      Loader._loadMapping (package:yaml/src/loader.dart:163)
#10     Loader._loadNode (package:yaml/src/loader.dart:83)
#11     Loader._loadDocument (package:yaml/src/loader.dart:63)
#12     Loader.load (package:yaml/src/loader.dart:55)
#13     loadYamlDocument (package:yaml/yaml.dart:53)
#14     loadYamlNode (package:yaml/yaml.dart:44)
#15     Pubspec.contents= (package:den/src/pub.dart:20)
#16     Pubspec.undepend.removeFromGroup (package:den/src/pub.dart:109)
#17     Pubspec.undepend (package:den/src/pub.dart:114)
#18     Den.uninstall.<anonymous closure> (package:den/src/den.dart:106)
#19     Object&ListMixin.fold (dart:collection/list.dart:200)
#20     Den.uninstall (package:den/src/den.dart:105)
#21     _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:539)
#22     _LocalInstanceMirror.delegate (dart:mirrors-patch/mirrors_impl.dart:414)
#23     DeclarationScript._handleSubCommands (package:unscripted/src/script_impl.dart:129)
#24     DeclarationScript._handleResults (package:unscripted/src/script_impl.dart:103)
#25     ScriptImpl.execute (package:unscripted/src/script_impl.dart:45)
#26     main (http://localhost:52691/den.dart:6)
#27     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:203)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:141)
orderedKeys: [browser, polymer, paper_elements]
Unhandled exception:
Error on line 11, column 19 of pubspec.yaml: Mapping values are not allowed in this context.
    paper_elements: '>=0.6.0 <0.7.0'
                  ^
#0      Scanner._fetchValue (package:yaml/src/scanner.dart:720)
#1      Scanner._fetchNextToken (package:yaml/src/scanner.dart:455)
#2      Scanner._fetchMoreTokens (package:yaml/src/scanner.dart:338)
#3      Scanner.peek (package:yaml/src/scanner.dart:319)
#4      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:423)
#5      Parser._stateMachine (package:yaml/src/parser.dart:88)
#6      Parser.parse (package:yaml/src/parser.dart:49)
#7      Loader._loadMapping (package:yaml/src/loader.dart:165)
#8      Loader._loadNode (package:yaml/src/loader.dart:83)
#9      Loader._loadMapping (package:yaml/src/loader.dart:163)
#10     Loader._loadNode (package:yaml/src/loader.dart:83)
#11     Loader._loadDocument (package:yaml/src/loader.dart:63)
#12     Loader.load (package:yaml/src/loader.dart:55)
#13     loadYamlDocument (package:yaml/yaml.dart:53)
#14     loadYamlNode (package:yaml/yaml.dart:44)
#15     Pubspec.contents= (package:den/src/pub.dart:20)
#16     Pubspec.undepend.removeFromGroup (package:den/src/pub.dart:109)
#17     Pubspec.undepend (package:den/src/pub.dart:114)
#18     Den.uninstall.<anonymous closure> (package:den/src/den.dart:106)
#19     Object&ListMixin.fold (dart:collection/list.dart:200)
#20     Den.uninstall (package:den/src/den.dart:105)
#21     _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:539)
#22     _LocalInstanceMirror.delegate (dart:mirrors-patch/mirrors_impl.dart:414)
#23     DeclarationScript._handleSubCommands (package:unscripted/src/script_impl.dart:129)
#24     DeclarationScript._handleResults (package:unscripted/src/script_impl.dart:103)
#25     ScriptImpl.execute (package:unscripted/src/script_impl.dart:45)
#26     main (http://localhost:37097/den.dart:6)
#27     _startMainIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:203)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:141)
```

With this project https://bitbucket.org/BenNG/polymer-dart-examples but modified pubspec.yaml

```
name: 'polym'
version: 0.0.1
description: >
  A starter template for a polymer.dart web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: '>=0.15.0 <0.16.0'
  paper_elements: '>=0.6.0 <0.7.0'

transformers:
- polymer:
    entry_points: web/index.html
```

Dart VM version: 1.9.0-edge.42259 (Wed Dec 10 10:45:21 2014) on "linux_x64"

**Comment by kaendfinger** [comment]
@seaneagan that bug is now marked as fixed. This can be closed if I'm correct.

**Comment by seaneagan** [comment]
@kaendfinger yep, thanks.
